<?php

namespace mmerlijn\forms\Http\Livewire;

use mmerlijn\forms\Classes\FormComponentTrait;
use Livewire\Component;

class Beoordeling extends Onderzoek
{
    public function mount()
    {
        $this->value['door'] = auth()->user()->name;
        $this->value['datum'] = date('Y-m-d');
        $this->updatedValue();
        parent::mount(); // TODO: Change the autogenerated stub


    }
    public function render()
    {
        return view('forms::livewire.beoordeling');
    }
}
